name: main
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-node-${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit Tests (Chrome)
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          command: npm run test:unit:ci
          timeout_minutes: 20
      - name: Package Build
        run: npm run package
      - name: Integration Tests (Chrome)
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          command: npm run test:integration:ci
          timeout_minutes: 20
      - name: Unit Tests (Firefox)
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          command: npm run test:unit:ci:firefox
          timeout_minutes: 20
      - name: Package Build
        run: npm run package
      - name: Integration Tests (Firefox)
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          command: npm run test:integration:ci:firefox
          timeout_minutes: 20

